name: distributed docker image build and push to docker hub

on:
  push:
    tags:
      - '*'

  workflow_dispatch:
    inputs:
      no-cache:
        description: "build images without cache"
        default: false
        required: false
        type: boolean

env:
  IMAGE_NAME: gha-runner
  AUTHOR: Mitsuru Shimamura <smbd.jp@gmail.com>
  TAG: latest

jobs:
  build-amd64:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set platform
        run: |
          platform=linux/amd64
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: extract docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: type=raw,value=${{ env.TAG }}
          labels: |
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.url=docker.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
            org.opencontainers.image.author=${{ env.AUTHOR }}


      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: build
        id: build-amd64
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=registry,push-by-digest=true,name-canonical=true
          cache-from: type=gha,scope=${{ env.PLATFORM_PAIR }}
          cache-to: type=gha,mode=max,scope=${{ env.PLATFORM_PAIR }}
          no-cache: ${{ inputs.no-cache == true }}

      - name: export digest
        run: |
          mkdir -p /tmp/artifacts
          digest="${{ steps.build-amd64.outputs.digest }}"
          touch "/tmp/artifacts/${digest#sha256:}"

      - name: upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digest-${{ env.PLATFORM_PAIR }}
          path: /tmp/artifacts/*
          if-no-files-found: error
          retention-days: 1

  build-arm64:
    runs-on: ARM64

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set platform
        run: |
          platform=linux/arm64
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: extract docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: type=raw,value=${{ env.TAG }}
          labels: |
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.url=docker.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
            org.opencontainers.image.author=${{ env.AUTHOR }}

      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: build
        id: build-arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=registry,push-by-digest=true,name-canonical=true
          cache-from: type=gha,scope=${{ env.PLATFORM_PAIR }}
          cache-to: type=gha,mode=max,scope=${{ env.PLATFORM_PAIR }}
          no-cache: ${{ inputs.no-cache == true }}

      - name: export digest
        run: |
          mkdir -p /tmp/artifacts
          digest="${{ steps.build-arm64.outputs.digest }}"
          touch "/tmp/artifacts/${digest#sha256:}"

      - name: upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digest-${{ env.PLATFORM_PAIR }}
          path: /tmp/artifacts/*
          if-no-files-found: error
          retention-days: 1

  merge-and-push:
    runs-on: ubuntu-latest
    needs: [ build-amd64, build-arm64 ]
    steps:
      - name: download artifatcs
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: create latest manifest and push
        run: docker buildx imagetools create -t docker.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME}}:latest $(printf 'ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}@sha256:%s ' *)
